apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    type: myapp-test
spec:
  replicas: 3
  selector: 
    matchLabels:
      type: myapp-test
  template:
    metadata:
      name: httpd-frontend
      labels: 
        type: myapp-test
    spec:
      containers:
        - name: httpd-frontend
          image: httpd:2.4-alpine 
  

